-- clear_synthetic_hearings.sql
-- Removes every hearing generated by migration 010 (is_synthetic = true).
-- Real hearings, the stated counts in case_listing_stats and the stated
-- reasons in case_adjournment_reasons are untouched.
--
-- Safe to run: no order or witness references a synthetic hearing (010 never
-- links them), so no foreign key blocks the delete.
--
-- To regenerate: rerun Part 2 of migration 010 (its INSERT INTO hearings,
-- with the SET LOCAL app.seed_anchor_date line), in one transaction.
--
-- Usage (psql):
--   psql "$DATABASE_URL" -f db/scripts/clear_synthetic_hearings.sql

BEGIN;

DELETE FROM hearings WHERE is_synthetic;

COMMIT;
