-- adjournment_analysis.sql
-- Which adjournment reasons dominate in which court and case type.
--
-- Usage (psql):
--   \i db/queries/adjournment_analysis.sql
--
-- Columns:
--   court            the case's current court (a transferred case counts
--                    under the court it is in now)
--   case_type        register code (GR, CC, NI, ...)
--   reason           adjournment reason, or 'not recorded'
--   adjournments     number of adjourned hearings
--   share_of_court   that count as a % of all adjournments in the court
--   synthetic        how many of those hearings were generated by migration
--                    010 (all of them, until real hearings are recorded)

SELECT co.name                                         AS court,
       ct.code                                         AS case_type,
       coalesce(h.adjournment_reason::text, 'not recorded') AS reason,
       count(*)                                        AS adjournments,
       round(100.0 * count(*)
             / sum(count(*)) OVER (PARTITION BY co.name), 1) AS share_of_court,
       count(*) FILTER (WHERE h.is_synthetic)          AS synthetic
FROM hearings h
JOIN cases c       ON c.id = h.case_id
JOIN courts co     ON co.id = c.court_id
JOIN case_types ct ON ct.id = c.case_type_id
WHERE h.outcome = 'adjourned'
  AND c.deleted_at IS NULL          -- archived cases are left out (019)
GROUP BY co.name, ct.code, h.adjournment_reason
ORDER BY adjournments DESC, court, case_type, reason;
